const secret = "Hey, did you know that in terms of male human and female pokemon breeding, that flareon may not be the best suited when compared to its cousins such as vaporeon or umbreon. But it's small physique and lightweight of 2'11\" and 25kg, it would serve a tight but usable delight for your tight desires.\
Along with its egg group of 'field' a Flareon is very capable of breeding with humanoid creatures unlike its cousin vaporeon. Its exp growth of medium to fast also allows it to quickly adjust to your body and what you desire, allowing for a more pleasurable experience. Flareon has a very impressive base attack and decent defences that are perfect for those who desire to be dominated, but its lower defensive stat allows you to return what it had given you, but its high special defence allow for all sorts of mental and emotional abuse, and it will power right through.\
Flareon does have an issue of its body reaching 1,700 degrees celsius, but as with other pokemon from the fire typing, they are not expressly immune to the flames, meaning that the genitalia would be much cooler as to not harm other Flareons, meaning it will provide a warm, but satiable hole. With Flareon's ability to learn moves such as endure, attract, stored power, charm, and scary face, it has the express ability to satiate the needs you want, being able to endure so much satisfaction, and charming you until you cum, then it will release all it has endured along with you.\
This is all without mentioning its other physical features. Flareon’s have manes of fur, ponytails and fluffy tails, the rest of their body covered in warm orange fur. This makes handling the Flareon easy as you’re able to grab the fur around its neck and manipulate it as you please, using it to choke or trap it from escaping. The tail makes it easier to latch onto as well, being able to stop it moving unless you want it to. The lack of protective fur around its chest makes its nipples easy to view and manipulate, allowing you freedom to use it as you please.\
In fact, one of Flareon’s hidden abilities is Guts, making it so that whenever the Flareon is affected by a status effect, their Attack increases by 50%, this means that you and your Flareon are able to get into some kinky situations! SO, should your Flareon be asleep and you need to relieve yourself, they’ll be immediately ready, giving back 1.5 times the pleasure as usual! This also works with paralyse, should your desires be to restrict your Flareon, allowing you complete freedom over its body. It’s that simple! Even more though, with your Flareon’s guts ability and its ability to learn sleep talk, you can perform played out rape for the weird people, and it can still use its increase sleeping damage to unconsciously return what you give it.\
But more than that, Flareon is the most huggable pokemon in terms of Human and Pokemon companionship. Not only is it able to warm its body up to the perfect hugging temperature, but it also has the aforementioned fluffy orange fur, that is no doubt incredibly soft. But more than this, because of its special defence stat, its able to withstand any emotional venting and be perfectly fine, meaning that a Flareon can cure your depression if treated right!\
There is no doubt that Vaporeon is the most compatible Pokemon when talking in terms of Male Human and Female Pokemon breedability, however Flareon is second second to none when comparing a long term relationship. Flareon has a resistance to any emotional damage meaning that they’ll be by your side no matter what, their high attack stat means that the Flareon will never fail to be able to please you, using every single skill in their arsenal to make you happy. Flareon’s body is practically designed for use, perfectly inviting and built for the long haul, the Flareon’s loyalty never failing to be by your side.\
KHHM\
Whenever I see Absol I can’t hold myself back, It takes every ounce in me to not splurg in my pants when I see the color’s white and blue. I have caught over ten thousand Absol’s to add to my rapindly increasing Absol harem and it’s only getting bigger. Absol is the only thing that turns me on, I stopped watching all porn the first time I saw Absol, my cock get’s unbelievably hard when I see her. When I mega evolved my first Absol baby batter immediately started spewing all over my room and gave my walls a new coat of paint. I have wet dreams about having sex with Absol every night, I would grab her horn and fuck her faster than a jackhammer. I have bought every pokemon game just so I can see Absol in each one, I spend all of my time staring at pictures of Absol. I even quit my job to pursue my new Absol passion, I love Absol so much. TLDR? I like Absol a bit.\
And for the fina punch\
I WANT TO FUCK BRAIXEN SO BAD I WANT TO SLURP UP HER LEGS LIKE BIG NOODLES I WANT TO EAT EVERY MEAL OF MY LIFE OFF OF HER FAT ASS I WANT TO DUMP MY CUM IN HER RUMP EVERY SINGLE NIGHT I WANT TO FUCK FUCK FUCK FUCK BRAIXEN SOOOOOOOOOOOOOOOOOOOO BAD PLEASE GOD FUCK I WANT TO BLAST ENDLESS BUSTS INTO HER LITTLE FOX WOMB I WANT TO GLAZE HER LIKE A DONUT WITH MY CUM FFFFFFFFUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUCK I WANNA PUMP PUMP FUCK FUCK HER FOX BUTT I WANT TO TASTE EVERY INCH OF HER BODY OOH MMMMYYY FUCKIIINNGGG GOOOOOOOOOOOOOOOOOOOOOOODDDDD PLEASE I WANT TO FUCK BRAIXEN I WANT TO FUCK BRAIXEN PLEASE PLEASE PLEASE IF I HAD A CHANCE TO FUCK BRAIXEN I WOULD NEVER CUM ANYWHERE ELSE BUT HER FOX PUSSYYYYYYY PLEASE PLEASE OMMGGG IM SO HORNY WHEN I SEE BRAIXEN I CANT STAND IT I HAVE TO FUCK BRAIXEN I WONT CUM TO ANYTHING BUT BRAIXEN HELP ME FUCK BRAIXEN SO HORNY FOR FOX ASS OMG PLEASE FUCK FUCK FUUUUUUUUUUUUUUUUUCKKKKKK OH MY FUCKING GOD IMAGINE BEING A POKEMON TRAINER AND SEEING HER FAT BUTT AND THIGHS BOUNCING WHEN FIGHTING I WOULD BE STRINGING CUMS SHOOTING FAT ROPES EVERY TIME I SAW HER FUCK FUCK FUCK I WANT TO FUCK BRAIXEN I WANT TO FUCK BRAIXEN\
jkjk\
Gardevoir is literally one of the most fuckable pokemon there are, you're just mad because you're in denial. Let's start with fact now, Gardevoir is 5'3\", this is not only the perfect height, but it means they can also have enough height to be able to do anything you want. While being 5\'3\", Gardevoir is also only 103LBs, so, theyre lite enough to pick up and have an all around good time. So, these are facts, not only this, but Gardevoir, LITERALLY, does not feel the pull of gravity, while also distorting dimensions.\
So, not only does this mean that Gardevoir can do anything they want ignoring gravity, but they are literally capable of making a pocket dimension in which yall can fuck in. These are all facts. Continuing with these facts, Gardevoir is telepathic and feels a strong emotion connection to their trainer, so, they will know before you that you\'re horny, she literally has it locked down and in the know before you\'re even aware of it, this only means that they are are able to serve their trainer in every way possible. So, these are just the facts on Gardevoir, but let's go even deeper so I can prove to you how Gardevoir is literally the most fuckable pokemon there is: Gardevoir can learn double team, so, now you get to fuck two of them.\
Gardevoir can learn charm, so, you thought you were horny before, but now it's compounded on itself. Finally, Gardevoir can learn mean look, combining this with double team, means not only do you get a tsundere on your dick, but also a submissive one. It's the best of both worlds. Gardevoir is literally the most fuckable pokemon there is and all of these are facts that yall are too afraid to realize.\
just stop already\
I know that a lot of people want to catch em' all, but my job is a much bigger challenge. It is my goal to masturbate to all 898 Pokemon, plain and simple. I usually try to do it twice a day, regardless of the difficulties. At the end, I always win. I go on places like Deviantart, rule 34 and, occasionally e621 in order to achieve this massive goal, and when I finally do, I will become a Pokemon Master. Sometimes, it is easy. I can come in five minutes looking at Gardevoir or Lopunny pornos. Sometimes I come across major challenges that I have to overcome, in the case of Garbodor and Magikarp especially. I have to imagine the wet, sloppy fish mouth sucking on my cock without thinking about the actual fish itself.\
It is very hard, but the satisfaction you get when you achieve victory is immense. Not only do you get the generally pleasurable feeling from ejaculation, but you also know that you overcame an obstacle few men have dared to try. I have a total of 347 successful ejaculations total, but it only gets harder as I move on. When I see a Serperior, for instance, I have to think to myself \"In what way can I imagine this creature in order to get off to it?\" It is a puzzle for sure, considering I do not have a thing for (most) of these creatures, making it extremely entertaining and interesting for others to watch. I try to focus in on its somewhat beautiful face, and think about that more than the yards of snake behind it.\
I sometimes have issues with Pokemon like Machamp, who appear extremely male. But I always find a way. There has been no hurdle too steep for me. I want to be the very best. Anything lower does not cut it. And that is why I am beating off to pictures of Lucario on the Internet, mom.\
okay let's end phiosophically\
\"Gotta catch 'em all!\" That's the popular sentence that most pokémon fans say. But for me, it's \"Catch-n-Smash 'em All!\". in-order to make Pokémon fans still happy with the Pokémon games. The Pokémon Company always have to make Sexy Mommy milkers looking pokémon to make the fans happy. Because Once the Hot Pokémon Enter the eyes. It gives a memetic effect that has a chance to make the subject who views it sexually attracted to it.\
The Pokémon Company THEMSELVES know that the fans are already sexually attracted to some pokémons. Like gardevoir or lopunny. And they still make hotter looking ones. Like cinderace and goodra. Like many other things on the internet. People make weird fricking fetishes. like vore. Which is the sexual practice of swallowing something alive. Even tho it's not possible in real life. Thus. The pokémon company HAD a reason to make the female-looking pokémons sexy. Because all of the weird crap that exist on the internet\
Also. Lopunny's design clearly makes \"her\" sexy. Even tho \"she\" is not an erotic character. The people who designed \"her\" clearly saw some pornography before. The proof is \"her\" juicy hips. People would try to have sexual pleasure with it. Since \"her\" hips are really REALLY wide.\
Also. Since the face-sitting fetish exists. Probably before the internet came in. Goodra is PERFECT for it. \"Her\" giant butt Is meant for it. Not also \"she\" is fat. Having sexual pleasure with \"Her\" Is clearly the perfect thing that exists in this big universe. \"Her\" farts are probably really attracting. Since \"she\" is big, slimy and fat. and of course. Thick\
Now for Cinderace. Lopunny's Best sexual friend. Cinderace's Foots Are pretty much great for foot fetish. \"Her\" Feet are really long and big. If you put \"her\" feet in your mouth. It's probably the tastiest thing in the world. Tickling \"her\" feet is pretty much fun for her and yourself. \"Her\" Feet smells like rose or even better.\
And now. for the most overrated one. Gardevoir. The queen of pokémons. Her mouth is probably the perfect thing for kissing. \"She\" would try to also kiss you if you would try to date \"her\". \"Her\" Lips feel like chewing a steak. Not only that. \"Her\" tongue is extremely flexible and long. And will dominate you in a tongue fight. Her moans sound really satisfying also.\
And that's pretty much it. You guys probably will call me a coomer but trust me. If pokémon was real. There would be a lot of human-pokémon hybrid organism. Anyways. I'll rather have a pokémon wife instead of a human one. smh";

export default secret;